# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('nationality', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genre', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=16)),
                ('watched', models.BooleanField(default=False)),
                ('stars', models.PositiveSmallIntegerField(choices=[(0, 'Bad'), (1, 'Regular'), (2, 'Good'), (3, 'Great')], default=1)),
                ('cast', models.ManyToManyField(null=True, to='film.Actor')),
            ],
        ),
    ]
