# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='cast',
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
