# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20160309_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='description',
        ),
        migrations.RemoveField(
            model_name='film',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='film',
            name='watched',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(to='film.Actor'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.Director'),
        ),
        migrations.AddField(
            model_name='award',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Film'),
        ),
    ]
