# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20160329_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(to='film.Actor'),
        ),
    ]
