# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20160330_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
