# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20160331_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
