# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_capital', models.FloatField(default=5)),
                ('final_capital', models.FloatField(default=5)),
                ('years', models.FloatField(default=5)),
                ('rate', models.FloatField(default=3.5)),
            ],
        ),
    ]
