# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20160128_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='final_capital',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='initial_capital',
            field=models.FloatField(null=True),
        ),
    ]
