# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='friendship_request',
            field=models.ManyToManyField(related_name='_member_friendship_request_+', to='social.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(related_name='_member_following_+', to='social.Member'),
        ),
    ]
