# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20160210_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='friendship_request',
            field=models.ManyToManyField(to='social.Member'),
        ),
    ]
